project:
  type: website
  output-dir: docs

website:
  title: "Diana Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd
      - resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

